### ISSUE TITLE
Compiling mlpack cpp files using shared library. library not found

### ISSUE THREAD

**Issue by pesoke** [conda-forge/mlpack-feedstock#23]
Issue:
I have installed mlpack via conda and importing it into python works. But when I try to compile cpp files using g++, I receive the error mlpack not found. I have included the location of libmlpack.so in my LD_LIBRARY_PATH and compiled with -lmlpack.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
armadillo                 9.200.7              hf4e8f56_0    conda-forge
arpack                    3.7.0                hc6cf775_1    conda-forge
binutils-meta             1.0.4                         0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_5    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
boost                     1.72.0           py38h9de70de_0    conda-forge
boost-cpp                 1.72.0               h7b93d67_1    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-compiler                1.0.4                h516909a_0    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py38h32f6830_0    conda-forge
compilers                 1.0.4                         0    conda-forge
cxx-compiler              1.0.4                hc9558a2_0    conda-forge
ensmallen                 2.12.1               hc0d2d6d_0    conda-forge
fortran-compiler          1.0.4                he991be0_0    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gfortran_impl_linux-64    7.5.0                hdf63c60_6    conda-forge
gfortran_linux-64         7.5.0               h09487f9_20    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_6    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
mlpack                    3.3.1            py38h5a835a2_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.18.5           py38h8854b6b_0    conda-forge
openblas                  0.3.6                h6e990d7_6    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pandas                    1.0.4            py38hcb8c335_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                47.3.1           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
superlu                   5.2.1             hfe2efc7_1207    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
active environment : mlpack
active env location : /home/pesoke/miniconda3/envs/mlpack
shell level : 1
user config file : /home/pesoke/.condarc
populated config files : 
conda version : 4.8.3
conda-build version : not installed
python version : 3.7.6.final.0
virtual packages : __glibc=2.12
base environment : /home/pesoke/miniconda3  (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
              https://repo.anaconda.com/pkgs/main/noarch
              https://repo.anaconda.com/pkgs/r/linux-64
              https://repo.anaconda.com/pkgs/r/noarch
package cache : /home/pesoke/miniconda3/pkgs
                /home/pesoke/.conda/pkgs
envs directories : /home/pesoke/miniconda3/envs
                    /home/pesoke/.conda/envs
platform : linux-64
user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/2.6.32-642.el6.x86_64 rhel/6.8 glibc/2.12
UID:GID : 34683:300
netrc file : None
offline mode : Falsecon

</details>

**Comment by marcelotrevisani** [comment]
Could you please inform the result of ``conda list`` or ``conda info``?
And how did you compiled it? Are you using the ``gcc`` available on ``conda-forge``?

**Comment by pesoke** [comment]
> Could you please inform the result of `conda list` or `conda info`?
I have updated the information.

> And how did you compiled it? Are you using the `gcc` available on `conda-forge`?
Yes, I used the conda-forge g++ compiler.

**Comment by marcelotrevisani** [comment]
which error did you receive from gcc? Could you please inform the full stacktrace ?

**Comment by pesoke** [comment]
$ g++ mlp_test.cpp -std=c++11 -lmlpack -larmadillo -lboost-serialization -fopenmp -L/path/to/shared/lib
mlp_test.cpp:1:10: fatal error: mlpack/core.hpp: No such file or directory
 #include <mlpack/core.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.


The compiler is not able to find the header file

**Comment by marcelotrevisani** [comment]
Ah ok
I think you will need to include the headers file as well
if you are using ``cmake`` you can add ``-DCMAKE_INCLUDE_PATH=$CONDA_PREFIX/include``
If you are calling ``gcc`` directly you can do ``-I$CONDA_PREFIX/include``

**Comment by marcelotrevisani** [comment]
Please let me know if it fixed the problem for you

**Comment by pesoke** [comment]
Your suggestion works. Thank you.
