### ISSUE TITLE
Remove upper limit on armadillo dependency

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/mlpack-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This package currently has an upper limit on its armadillo dependency of armadillo <10.0a0.  However, based on [this exchange](https://github.com/mlpack/ensmallen/issues/357#issuecomment-1418283315), it seems that this should not be a restriction on this package.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by rcurtin** [comment]
I think that with the ensmallen fix in conda-forge/ensmallen-feedstock#35 this should be fixed too. Feel free to reopen if not. :+1:
